[project]
name = "agapis-lapis"
version = "0.2.1"
description = "A love quotes generator app... Or is it?"
readme = "README.md"
requires-python = ">=3.13"
authors = [{ name = "MetaDusk", email = "andredcxxv@gmail.com" }]
license = { text = "AGPL-3.0" }

dependencies = [
    "cerebras-cloud-sdk>=1.67.0",
    "flet>=0.81.5",
    "python-dotenv>=1.2.1",
]

[dependency-groups]
dev = [
    "flet-cli>=0.81.0",
    "flet-desktop>=0.81.0",
    "flet-web>=0.81.0",
    "tomlkit>=0.13.3",
]

[tool.flet]
org = "com.metadusk"
product = "Agapis Lapis"
company = "MetaDusk Inc."
copyright = "Copyright (C) 2025 MetaDusk"
compile_app = true
compile_packages = true
cleanup_on_compile = true
build_number = 1

[tool.flet.assets]
include = ["assets"]

[tool.flet.splash]
color = "#ffffff"
dark_color = "#1c2120"

[tool.flet.app]
path = "src"

[tool.flet.app.boot_screen]
show = true
message = "Booting up Agapis Lapis..."

[tool.flet.app.startup_screen]
show = true
message = "Starting Agapis Lapis..."

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
